### ISSUE TITLE
Wont Compile on ubuntu

### ISSUE THREAD

**Issue by waterfallm** [CryptoFlowCoin/CryptoFlowCoin#2]
Hi when trying to compile on Ubuntu 18.04 i get the following error.

Makefile:595: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by pedro-at-decenomy** [comment]
Hi @waterfallm it should compile on version 1.3 with the included build scripts

execute `bash <( curl -sL https://raw.githubusercontent.com/CryptoFlowCoin/CryptoFlowCoin/master/build_linux.sh)`
